// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package proc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfEvent struct {
	_           structs.HostLayout
	Pid         uint32
	Kind        uint32
	Nargs       uint32
	_           [4]byte
	TsNs        int64
	ExitCode    int32
	HasExitCode uint8
	Args        [1536]int8
	_           [3]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapEvents           = "events"
	bpfMapExecs            = "execs"
	bpfMapHeap             = "heap"
	bpfProgHandleExecve    = "handle_execve"
	bpfProgHandleExit      = "handle_exit"
	bpfProgHandleExitGroup = "handle_exit_group"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	HandleExecve    *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleExit      *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleExitGroup *ebpf.ProgramSpec `ebpf:"handle_exit_group"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
	Execs  *ebpf.MapSpec `ebpf:"execs"`
	Heap   *ebpf.MapSpec `ebpf:"heap"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events *ebpf.Map `ebpf:"events"`
	Execs  *ebpf.Map `ebpf:"execs"`
	Heap   *ebpf.Map `ebpf:"heap"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Execs,
		m.Heap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	HandleExecve    *ebpf.Program `ebpf:"handle_execve"`
	HandleExit      *ebpf.Program `ebpf:"handle_exit"`
	HandleExitGroup *ebpf.Program `ebpf:"handle_exit_group"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.HandleExecve,
		p.HandleExit,
		p.HandleExitGroup,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
