name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Go
      uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
      with:
        go-version: '1.25.0'

    - name: Download dependencies
      run: go mod download

    - name: Run all tests (Unit, Integration, and E2E)
      # We run everything with sudo so the eBPF/fanotify tests execute fully
      run: sudo go test -v ./...
