name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

    - name: Set up Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.25.0'

    - name: Download dependencies
      run: go mod download

    - name: Run all tests (Unit, Integration, and E2E)
      # We run everything with sudo so the eBPF/fanotify tests execute fully
      run: sudo go test -v ./...
